### ISSUE TITLE
Mostrar teclado numérico no campo RG e telefone

### ISSUE THREAD

**Issue by danielfleck** [ddtq/saude-app#5]

**Comment by danielfleck** [comment]
<input type="text" pattern="[0-9]*">                     ??????

**Comment by danielfleck** [comment]
\<input type="text" pattern="[0-9]*"\>  ????

**Comment by felipe-maia** [comment]
Testei isso não funciona. Instalei 3 bibliotecas de máscara mas todas são erro na hora de implementar, estou seguindo a documentação mas mesmo assim dão erroEm 27 de mar de 2020 10:53, Daniel Rodrigo Fleck <notifications@github.com> escreveu:
<input type="text" pattern="[0-9]*">  ????
